workflows:
  cordova:
    name: Apache Cordova
    environment:
      vars:
        GRADLE_PATH: /_Release
    scripts:
     - sudo npm install -g cordova
     - npm install
     - cordova platform add android
     - PATH=$PATH:$GRADLE_PATH cordova build android
