workflows:
  cordova:
    name: Apache Cordova
    environment:
      vars:
        GRADLE_PATH: /Users/builder/programs/gradle-5.6.4/bin
    scripts:
     - sudo npm install -g cordova
     - npm install
     - cordova platform add android
      - PATH=$PATH:$GRADLE_PATH cordova build android
  publishing:
    email:
      recipients:
        - chuijiyang1999@gmail.com
      notify:
        success: true
        false: true
